<?php

namespace BCLib\MetaLib;

class LoginCommand extends Command
{
    public function __construct()
    {
        $op = 'login_request';
        $param = [
            'user_name'     => $this->_user_name,
            'user_password' => $this->_password
        ];
        $require_login = false;
        $response_reader = new LoginCommand();
        parent::__construct($op, $params, $require_login, $response_reader); // TODO: Change the autogenerated stub
    }

}